<?php
session_start();
include_once("../config.php");
unset($_SESSION["login"]);
unset($_SESSION["idsuario"]);
unset($_SESSION["nivel"]);
unset($_SESSION["horasesion"]);
unset($_SESSION["idmenu"]);
unset($_SESSION["subm"]);
session_destroy();
header("Location:$url$directory/");
?>